AWSTemplateFormatVersion: "2010-09-09"
Description: "Granting permission to Shweta to list AWS IAM Users"

Resources:
  TestIAMPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "TestIAMPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action: "iam:ListUsers"
          Resource: "*"
      Users:
      - "Shweta"
