AWSTemplateFormatVersion: "2010-09-09"
Description: "Give Sheweta Permissio to see the EC2 instances"

Resources:
  TestPolicy02:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "TestPolicy02"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action: "ec2:DescribeInstances"
          Resource: "*"
      Users:
      - "Sheweta"
