AWSTemplateFormatVersion: "2010-09-09"
Description: "Give user : Priyanka Permission to create an EC2 Instance"

Resources:
  TestPolicy05:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "AllowEC2Creation"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "ec2:RunInstances"
          - "ec2:DescribeInstances"
          - "ec2:TerminateInstances"
          Resource: "*"
      Users:
      - "Priyanka"
