AWSTemplateFormatVersion: "2010-09-09"
Description: "Give Sheweta Permissio to see the EC2 instances"

Resources:
  TestPolicy03:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "TestPolicy03"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action: "ec2:Describe*"
          Resource: "*"
      Users:
      - "Shweta"
