AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an AWS IAM User"

Resources:
  TestUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "Shweta"

      Tags:
      - Key: "User Name"
        Value: "Shweta"

      LoginProfile:
        Password: "Apple@123$ecure"
        PasswordResetRequired: false
