AWSTemplateFormatVersion: "2010-09-09"
Description: "Sexy Lady on the Floor"

Resources:
  TestGroup07:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TestGroup07
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEC2FullAccess

  AddUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref TestGroup07
      Users:
      - Julia
