AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template to create an EC2 instance"

Resources:
  ProdServer05:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-09fe153fd4143fcde"
      InstanceType: "t2.micro"
      KeyName: "EC2KeyPair07"
      Tags:
      - Key: "Name"
        Value: "Prod-Server05"

  TestEBSVolume:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: "us-east-1a"
      Size: 8
      VolumeType: "gp2"
      Tags:
      - Key: "Name"
        Value: "TestEBSVolume"

  AttachEBSVolume:
    Type: "AWS::EC2::VolumeAttachment"
    Properties:
      Device: "/dev/sdf"
      InstanceId: !Ref ProdServer05
      VolumeId: !Ref TestEBSVolume

  TestKeyPair:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: "EC2KeyPair07"
