AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an AWS IAM User"

Resources:
  TestUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "Aishwarya"

      Tags:
      - Key: "User Name"
        Value: "Aishwarya"
