AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create an EC2 instance

Parameters:
  EnvironmentName:
    # logical name of the parameter
    Type: String
    Default: Dev
    AllowedValues:
    - Dev
    - Test
    - Prod

Mappings:
  EnvMap:
    # logical name of the mapping
    Dev:
      instanceType: "t2.micro" # Amazon Windows Server 2019 Base
      name: "Dev-EC2-Instance"
    Test:
      instanceType: "t2.small"
      name: "Test-EC2-Instance"
    Prod:
      instanceType: "t2.medium"
      name: "Prod-EC2-Instance"

Resources:
  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable RDP access via port 3389
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3389
        ToPort: 3389
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: Test-Security-Group01

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-09fe153fd4143fcde # Amazon Windows Server 2019 Base
      InstanceType: !FindInMap [ EnvMap, !Ref EnvironmentName, instanceType ]
      KeyName: !Ref NewKeyPair
      SecurityGroupIds:
      - !GetAtt TestSecurityGroup.GroupId
      Tags:
      - Key: Name
        Value: !FindInMap [ EnvMap, !Ref EnvironmentName, name ]

  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: MyKeyPair02 # Replace with your desired key pair name  
      KeyType: rsa
      Tags:
      - Key: Name
        Value: MyKeyPair02

Outputs:
  InstanceId:
    Description: "InstanceId of the newly created EC2 instance"
    Value: !Ref EC2Instance
