AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create an EC2 instance

Parameters:
  EnvironmentName:  # logical name of the parameter
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - Prod

Mappings:
  EnvMap: # logical name of the mapping
    Dev:
      instanceType: "t2.micro"  # Amazon Windows Server 2019 Base
      name: "Dev-EC2-Instance"
    Test:
      instanceType: "t2.small"
      name: "Test-EC2-Instance"
    Prod:
      instanceType: "t2.medium"
      name: "Prod-EC2-Instance"

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable RDP access via port 3389
      VpcId: vpc-0f0cd80060690caa0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: 10.0.0.0/8  # Restrict to private network range 

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-09fe153fd4143fcde  # Amazon Windows Server 2019 Base
      InstanceType: !FindInMap [EnvMap, !Ref EnvironmentName, instanceType]
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds: 
        - !Ref TestSecurityGroup
      SubnetId: subnet-xxxxxxxxx  # Replace with your subnet ID
      EbsOptimized: true
      Monitoring: true
      Tags:
        - Key: Name
          Value: !FindInMap [EnvMap, !Ref EnvironmentName, name]