AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an EC2 Instance using a Launch Template"

Parameters:
  LaunchTemplateId:
    Type: String
  LaunchTemplateVersion:
    Type: String

Resources:
  EC2Instance01:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateVersion

Outputs:
  InstanceId:
    Description: "ID of the EC2 Instance"
    Value: !Ref EC2Instance01
