AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an AWS IAM Group / Role and assign  Permissions"

Resources:
  TestAWSGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TestAWSGroup56

  TestAWSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TestAWSRole56
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            AWS: !GetAtt TestAWSGroup.Arn
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEC2FullAccess
