AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template to create anAW IAM Role allowing to create an EC2 Instance"

Resources:
  EC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "EC2InstanceRole01"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "ec2.amazonaws.com"
          Action: "sts:AssumeRole"
      Policies:
      - PolicyName: "EC2InstancePolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "ec2:RunInstances"
            - "ec2:DescribeInstances"
            - "ec2:TerminateInstances"
            - "ec2:CreateTags"
            - "ec2:DescribeImages"
            - "ec2:DescribeKeyPairs"
            - "ec2:DescribeSecurityGroups"
            - "ec2:DescribeSubnets"
            - "ec2:DescribeVpcs"
            - "ec2:CreateSecurityGroup"
            - "ec2:AuthorizeSecurityGroupIngress"
            - "ec2:RevokeSecurityGroupIngress"
            - "ec2:DeleteSecurityGroup"
            - "ec2:AuthorizeSecurityGroupEgress"
            - "ec2:RevokeSecurityGroupEgress"
            - "ec2:DeleteSecurityGroup"
            - "ec2:CreateVolume"
            - "ec2:AttachVolume"
            - "ec2:DetachVolume"
            - "ec2:DeleteVolume"
            - "ec2:DescribeVolumes"

            Resource: "*"
