AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an EC2 Instance using a Launch Template using nesting"

Resources:
  MyLaunchTemplateStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://awsskyline056.s3.us-east-1.amazonaws.com/ec2launchtemplate.yml"

  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-09fe153fd4143fcde"
      LaunchTemplate:
        LaunchTemplateId: !GetAtt MyLaunchTemplateStack.Outputs.LaunchTemplateId
        Version: !GetAtt MyLaunchTemplateStack.Outputs.LaunchTemplateVersion
